version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql_container_pictures
    restart: always
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'password'
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: volume
        source: my_db
        target: /var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer_container_pictures
    restart: always
    ports:
      - 8080:8080
volumes: 
  my_db: